print("Hola mundo!")
print("Hola otra vez!")
print("Me gusta escribir esto")
print("Esto es divertido")
# print("Hey! imprimiendo")
print("Preferiría que 'no'")
print("He 'dicho' que no toques esto")
print("Pull of this!!")
